// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathFlowerPing = "/Flower.service.v1.Flower/Ping"
var PathFlowerSayHello = "/Flower.service.v1.Flower/SayHello"
var PathFlowerSayHelloURL = "/kratos-Flower/say_hello"

// FlowerBMServer is the server API for Flower service.
type FlowerBMServer interface {
	Ping(ctx context.Context, req *google_protobuf1.Empty) (resp *google_protobuf1.Empty, err error)

	SayHello(ctx context.Context, req *HelloReq) (resp *google_protobuf1.Empty, err error)

	SayHelloURL(ctx context.Context, req *HelloReq) (resp *HelloResp, err error)
}

var FlowerSvc FlowerBMServer

func flowerPing(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := FlowerSvc.Ping(c, p)
	c.JSON(resp, err)
}

func flowerSayHello(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := FlowerSvc.SayHello(c, p)
	c.JSON(resp, err)
}

func flowerSayHelloURL(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := FlowerSvc.SayHelloURL(c, p)
	c.JSON(resp, err)
}

// RegisterFlowerBMServer Register the blademaster route
func RegisterFlowerBMServer(e *bm.Engine, server FlowerBMServer) {
	FlowerSvc = server
	e.GET("/Flower.service.v1.Flower/Ping", flowerPing)
	e.GET("/Flower.service.v1.Flower/SayHello", flowerSayHello)
	e.GET("/kratos-Flower/say_hello", flowerSayHelloURL)
}
